import { useLocation } from "@docusaurus/router";
import ScriptTag from "react-script-tag";
import useHashDetails from "../../components/useHashDetails";
import { toggleAllItems } from "../../components/toggleAllItems";

import JavascriptSupportItem from "../../components/JavascriptSupportItem";
// NOTE: _std-data.json is generated by the Makefile build process (don't manually edit it!) and we prepend the filename with _ so Docusaurus does not try to render it as its own page (because it is inside src/pages):
import stdData from "./_std-data.json";

function JsSupport() {
  const location = useLocation();
  const hash = location.hash ? location.hash.substring(1) : undefined;
  const properties = Object.entries(stdData).filter(
    (entry) => !["name", "__princetype__", "desc"].includes(entry[0])
  );

  useHashDetails();

  const toggleAllJS = (event) =>
    toggleAllItems(event, "js-support-table", "toggle-js");

  return (
    <div>
      <div className="markdown">
        <p>
          Prince supports most of ECMAScript 5th edition, but not strict mode.
          Later editions of ECMAScript are not supported.
        </p>
        <p>
          The following table shows supported JavaScript objects, methods and
          properties. For more details, see also{" "}
          <a href="/doc/javascript#js-prince">JavaScript in Prince</a>.
        </p>
        <p>
          * objects, methods and properties marked with an asterisk are Prince
          extensions.
        </p>
        <p>
          Objects, methods and properties{" "}
          <span className="dep">with a line-through</span> are deprecated,
          support might be removed in a future Prince version.
        </p>

        <p className="toggle">
          <a href="#" onClick={toggleAllJS} id="toggle-js">
            Toggle (open/close) all properties
          </a>
        </p>

        <div className="js-overview level" id="js-support-table">
          <JavascriptSupportItem
            path={["window"]}
            name="window"
            princetype={stdData.__princetype__}
            desc={stdData.desc}
            open={true}
            properties={properties}
            hash={hash}
          />
        </div>
      </div>
    </div>
  );
}

export default JsSupport;
